name: Build Archive
on:
  push:
    branches:
      - master
jobs:
  publish:
    name: Build
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        include:
        - device: android
          name: Android
          command: android -t apk
        - device: ios
          name: IOS
          command: ios -t simulator          
    
    steps:
      - name: sei la ne
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: yarn install
      - run: echo ${{ matrix.command }}
      
        env:
          EXPO_APPLE_ID: 1
          EXPO_APPLE_PASSWORD: 23s
